// Generated by Isabelle-LLVM. Do not modify.
#ifndef _ISASAT_RESTART_H
#define _ISASAT_RESTART_H 1



typedef struct CLAUSE CLAUSE;
typedef struct CLAUSES CLAUSES;



typedef int8_t CBOOL;
typedef struct CLAUSE {
  int64_t size;
  struct {
    int64_t used;
    uint32_t*clause;
  };
} CLAUSE;
typedef struct CLAUSES {
  int64_t num_clauses;
  CLAUSE*clauses;
} CLAUSES;
typedef int8_t PROFILE_CST;
typedef int32_t* STRING_VERSION;

STRING_VERSION llvm_version();
PROFILE_CST IsaSAT_Profile_GC();
PROFILE_CST IsaSAT_Profile_REDUCE();
PROFILE_CST IsaSAT_Profile_ANALYZE();
PROFILE_CST IsaSAT_Profile_PROPAGATE();
PROFILE_CST IsaSAT_Profile_MINIMIZATION();
PROFILE_CST IsaSAT_Profile_INITIALISATION();

#endif
