theory Watched_Literals_Algorithm_Restart
imports Watched_Literals_Algorithm Watched_Literals_Transition_System_Restart
  Watched_Literals_Transition_System_Reduce
  Weidenbach_Book_Base.Explorer
begin


end
